### ISSUE TITLE
How to create custom template?

### ISSUE THREAD

**Issue by edap** [mattdesl/canvas-sketch#100]
Hello, I would like to create a custom template with custom index.html and a custom.js file. I have found here https://github.com/mattdesl/canvas-sketch/issues/13 information regarding how to create the custom .js file, but I did not found anything regarding the html file

**Comment by mattdesl** [comment]
The `.html` is currently always the same (the templates won't change the HTML, only the JS), but you can override it with the `--html` flag.

What I'd suggest is using a shell alias, if you are using a terminal that supports it. For example, putting the following in a `~/.bashrc` or `~/.bash_profile` file:

```sh
alias mysketch="canvas-sketch --template=/path/to/script.js --html=/path/to/index.html"
```

Then you can run it like normal:

```sh
# uses your custom HTML + JS
mysketch sketch.js --new

# uses your custom HTML
mysketch test.js --build --dir=dist/ --name=index
```

**Comment by edap** [comment]
Many thanks Matt for the detailed answer. I am able to create my custom html and js templates. I have another problems now but related to other issues.
