### ISSUE TITLE
Willing to Partcipate

### ISSUE THREAD

**Issue by Royaljerry** [mattdesl/canvas-sketch#11]
Hi Matt, you mentioned in the lead you’re looking for collaborators. Here I am. Been into generative artistry for ten years (CFDG, some Processing, native JS and Python), so I instantly became enthusiastic about this project. Feel free to contact me at royaljerry@gmail.com – some works and experiments are to be found at https://www.behance.net/royaljerry Cheers, Adam

**Comment by mattdesl** [comment]
Thanks! Glad to hear you are enthusiastic. :smile: 

What would be most helpful at this point is to have users with a variety of different needs/interests testing the tool, seeing what sort of features are working really well and which features are not working so well, thinking of ways to improve the tool, etc. Once things move a bit further along, we could start looking into a frontend (I have a basic version, but want to revisit the design), better docs, etc.

**Comment by mattdesl** [comment]
Closing this just to clean up some issues.
