### ISSUE TITLE
Programmatically trigger export for penplot

### ISSUE THREAD

**Issue by Andrewglass1** [mattdesl/canvas-sketch#122]
Hello,

Is it possible to automatically trigger an svg export for a penplot sketch using canvas-sketch-cli?  Thank you and thank you for this incredibly helpful library.

**Comment by mattdesl** [comment]
I don't think it's possible triggering it from the Node.js CLI at the moment. If you are in the frontend (the client JS) you can run `props.exportFrame()` from your code, e.g. triggering it from a window level event (mouse click, or maybe even a websocket message).

**Comment by mattdesl** [comment]
Closing as hopefully `exportFrame` should suffice.
