### ISSUE TITLE
Unable to save streams

### ISSUE THREAD

**Issue by tomssem** [mattdesl/canvas-sketch#133]
Every time I try to save a stream of frames (with out without the `--stream` option, and if set to `gif` or not) I get a `TypeError` along the lines of:
```
/usr/local/lib/node_modules/canvas-sketch-cli/src/middleware.js:189
            if (mimeType && mimeType !== currentStream.encoding) {
                                                       ^

TypeError: Cannot read property 'encoding' of null
    at /usr/local/lib/node_modules/canvas-sketch-cli/src/middleware.js:189:56
    at /usr/local/lib/node_modules/canvas-sketch-cli/node_modules/mkdirp/index.js:49:26
    at FSReqCallback.oncomplete (fs.js:159:5)
```

The exact property that is null can be different, another example being:
```
/usr/local/lib/node_modules/canvas-sketch-cli/src/middleware.js:198
                  currentStream.writeBufferFrame(buf)

TypeError: Cannot read property 'writeBufferFrame' of null
```

**Comment by GusHebblewhite** [comment]
I'm getting the same issue. Win 11.

**Comment by GusHebblewhite** [comment]
Tried to actually find the bug but it's above my JS paygrade - in essence `handleStreamEnd` gets called in between `usingStream` being defined and `currentStream` being used in the if statement, so in that time `currentStream` is set to null.

**Comment by mattdesl** [comment]
Thanks! Gonna look into this. I haven't noticed any errors on my end so a bit tricky for me to debug. Can you be sure you are on the latest version of both `canvas-sketch` and `canvas-sketch-cli` ? 

```sh
# install latest CLI locally or globally depending on what you use
npm install canvas-sketch-cli@latest --global

# install latest API locally into your repo
npm install canvas-sketch@latest --save
```

**Comment by cumenez** [comment]
Hi, I have the same issue, I have the latest version of both canvas-sketch and canvas-sketch-cli, when i stop the stream it give me the error, and save the stream on download although I specified the ouput path.

**Comment by david-huck** [comment]
+1, i get the same error message as OP

**Comment by Dot-Rhs** [comment]
I've recently hit this issue, I don't have a fix but I have a workaround I can't really explain, at least it works in my case. 

I've  gone to middleware.js, line 189 and just logged currentStream. 
I can save video's now although there is just a terminal full of logs now, if I remove the log the error returns. 

Does anyone with more experience have an insight into why that would happen?

**Comment by chetankumar** [comment]
I finally figured it out. Just as @Dot-Rhs pointed out, the trouble is in line number 189. I think that section was added very recently  to stop some incompatible encoding from being saved. I just commented out the below code around # 189.

`// if (mimeType && mimeType !== currentStream.encoding) {
 //   reject(new Error('Error: Currently only single-image exports in image/png or image/jpeg format is supported with MP4 streaming'));
 // }`

Only caveat, you need to remember that for an mp4 stream, the encoding in the options should be 'image/png' or 'image/jpeg'. The above section of code "enforced" that. Trouble is, it enforced that without checking if the stream is null.

**Comment by lancesnider** [comment]
> I finally figured it out. Just as @Dot-Rhs pointed out, the trouble is in line number 189. I think that section was added very recently to stop some incompatible encoding from being saved. I just commented out the below code around # 189.
> 
> `// if (mimeType && mimeType !== currentStream.encoding) { // reject(new Error('Error: Currently only single-image exports in image/png or image/jpeg format is supported with MP4 streaming')); // }`
> 
> Only caveat, you need to remember that for an mp4 stream, the encoding in the options should be 'image/png' or 'image/jpeg'. The above section of code "enforced" that. Trouble is, it enforced that without checking if the stream is null.

You're talking about the line in `middleware.js` in `canvas-sketch-cli`, right? Can you tell me how to do that in the globally installed version of `canvas-sketch-cli`? Thanks.

**Comment by mattdesl** [comment]
I believe this should now be fixed in latest. Please update like so:

(if you've installed the CLI globally previously)

```sh
npm install canvas-sketch-cli@latest --global
```

Or locally:

```sh
npm install canvas-sketch-cli@latest --save-dev
```

Let me know if any issues persist.

**Comment by vahlcode** [comment]
I'm still facing same problem here.

`There was a problem starting the stream export`

**Comment by vahlcode** [comment]
Worked after installing locally.
