### ISSUE TITLE
Cannot install - Permission & Depreciation warning (unsolved)

### ISSUE THREAD

**Issue by Pi-Kay** [mattdesl/canvas-sketch#135]
Hi, 

I have trouble with the installation on my Mac. I appreciate any help with this. 

I get a permission error. If I repeat the installation command with sudo, I get warnings "WARN deprecated". 
The advice on the links in the text didn't help so far. 

Did anyone have the same problem? 

Details:

npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/canvas-sketch-cli
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/canvas-sketch-cli'
npm ERR! [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/canvas-sketch-cli'] {
npm ERR! errno: -13,
npm ERR! code: 'EACCES',
npm ERR! syscall: 'mkdir',
npm ERR! path: '/usr/local/lib/node_modules/canvas-sketch-cli'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/creative/.npm/_logs/2021-12-25T20_57_23_165Z-debug-0.log
creative@Petras-MBP ~ % % sudonpm install canvas-sketch-cli -g
fg: no current job
creative@Petras-MBP ~ % % sudo
fg: no current job
creative@Petras-MBP ~ % install canvas-sketch-cli -g
install: canvas-sketch-cli: No such file or directory
creative@Petras-MBP ~ %
[Restored 25 Dec 2021 at 21:08:41]
Last login: Sat Dec 25 21:06:59 on console
Restored session: Sat 25 Dec 2021 21:02:41 WET
creative@Petras-MBP ~ % sudo npm install canvas-sketch-cli -g
Password:
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

**Comment by mattdesl** [comment]
Hello, you can try the steps here to see if that resolves the issue:

https://github.com/mattdesl/canvas-sketch/issues/125#issuecomment-1003946650

**Comment by czielks** [comment]
when i run the above to start a new project, i get the following
npx canvas-sketch src/sketch 2.js --new --open

Currently only one entry is supported.

Example usage:
    canvas-sketch src/index.js

    at prepare (/Users/calebzielke/Documents/Creative/Sketches/node_modules/canvas-sketch-cli/src/index.js:450:13)
    at Module.start [as exports] (/Users/calebzielke/Documents/Creative/Sketches/node_modules/canvas-sketch-cli/src/index.js:146:17)
    at Object.<anonymous> (/Users/calebzielke/Documents/Creative/Sketches/node_modules/canvas-sketch-cli/src/index.js:620:10)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

How do start and run a new project since "one one entry is supported"

**Comment by mattdesl** [comment]
Closing. Anyone running into issues, also see here:

https://github.com/mattdesl/canvas-sketch/issues/96
