### ISSUE TITLE
Cannot Install npm install canvas-sketch-cli -g

### ISSUE THREAD

**Issue by EvengeloJ** [mattdesl/canvas-sketch#139]
Hi, 

I am not an expert, sorry if this is a stupid question :-), but I come across the following issue when I try to install npm canvas-sketch:

npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

added 644 packages, and audited 645 packages in 6s

48 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (3 moderate, 5 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

**Comment by fturcheti** [comment]
Hey @EvengeloJ! These are not errors, just warnings. They're outputted even when the installation is successful. Have you tried to run `canvas-sketch` after this? You can follow this article to make your first sketch: https://github.com/mattdesl/canvas-sketch/blob/master/docs/hello-world.md

**Comment by EvengeloJ** [comment]
When I type in this command: canvas-sketch sketch-.js --new, it will be stuck as follows: 

C:\Users\Evengelo\Documents\JAVASCRIPT\sketches
λ canvas-sketch sketch-.js --new

  → Writing file: sketch-.js

  → Generating default "package.json" file

  → Installing dependencies:
    canvas-sketch


added 28 packages, and audited 29 packages in 1s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[0005] info  Server running at http://192.168.1.151:9966/ (connect)
[0005] info  LiveReload running
[0005] 399ms      264KB (browserify)

**Comment by EvengeloJ** [comment]
@fturcheti Thanks for your quick reply. I will try. :-)

**Comment by fturcheti** [comment]
@EvengeloJ You're welcome! Don't forget to come back and close the issue if everything goes well.
