### ISSUE TITLE
Output is not working as I'd expect

### ISSUE THREAD

**Issue by uxwellbeing** [mattdesl/canvas-sketch#142]
Hi, I tried `commend+S` many times.  Though the canvas-sketch is working, the `.png` file saved are not the same shape in the browser.

**Comment by fturcheti** [comment]
Depending on the way your code is structured, this can happen. Can you share your code here?

**Comment by hjco** [comment]
Same problem, output not work.

**OS**: Linux 5.10.105-1-MANJARO x86_64 GNU/Linux
**Node version**: v14.15.5
**Error**: Nothing in the console
**Instalation mode**:  npm install canvas-sketch-cli -g, yarn global canvas-sketch-cli, sudo npm install -g canvas-sketch-cli 
**Canvas cli**: 
```
canvas-sketch sketch.js --output=output/
CANVAS_SKETCH_OUTPUT=./outputs canvas-sketch sketch.js  
```

**Code**: the sketch canvas-sketch-cli auto generate file the first time

**Comment by skyler072** [comment]
Does anyone have any update on this? I'm having the same issue

**Comment by mattdesl** [comment]
Going to close as the steps above should hopefully resolve things. Please comment if there is further issue.
