### ISSUE TITLE
-bash: canvas-sketch: command not found

### ISSUE THREAD

**Issue by snoodler** [mattdesl/canvas-sketch#143]
Hi, I am having issues running canvas-sketch

These are my outputs:

mac:sketches raularellano$ npm config get prefix
/usr/local
mac:sketches raularellano$ echo $PATH
/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Little Snitch.app/Contents/Components:/opt/X11/bin

thanks for the help

**Comment by fturcheti** [comment]
Your npm configuration seems to be ok. What's the output of `npm install canvas-sketch-cli -g`?

**Comment by snoodler** [comment]
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/canvas-sketch-cli
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/canvas-sketch-cli'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/canvas-sketch-cli'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/canvas-sketch-cli'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/raularellano/.npm/_logs/2022-02-17T12_35_38_557Z-debug-0.log
rauls-mac:sketches raularellano$

**Comment by fturcheti** [comment]
@snoodler You can try to fix your npm installation following these instructions: [Fixing EACCESS Error on npm install -g](https://github.com/mattdesl/canvas-sketch/blob/master/docs/troubleshooting.md#fixing-eaccess-error-on-npm-install--g). Or you can try to [install canvas-sketch CLI locally](https://github.com/mattdesl/canvas-sketch/blob/master/docs/installation.md#installing-the-cli-locally).

**Comment by chigau-cloud** [comment]
Same issue here, installing locally doesn't solve it either

**Comment by snoodler** [comment]
does this help?

npm install canvas-sketch-cli@latest -g
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

added 650 packages, and audited 651 packages in 32s

46 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (3 moderate, 5 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
-mac:sketches me$ npm audit
# npm audit report

ansi-regex  >2.1.1 <5.0.1
Severity: moderate
 Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
No fix available
node_modules/ora/node_modules/ansi-regex
  strip-ansi  4.0.0 - 5.2.0
  Depends on vulnerable versions of ansi-regex
  node_modules/ora/node_modules/strip-ansi
    ora  2.0.0 - 4.0.2
    Depends on vulnerable versions of strip-ansi
    node_modules/ora
      canvas-sketch-cli  *
      Depends on vulnerable versions of budo
      Depends on vulnerable versions of ora
      node_modules/canvas-sketch-cli

glob-parent  <5.1.2
Severity: high
Regular expression denial of service - https://github.com/advisories/GHSA-ww39-953v-wcq6
No fix available
node_modules/glob-parent
  chokidar  1.0.0-rc1 - 2.1.8
  Depends on vulnerable versions of glob-parent
  node_modules/chokidar
    budo  >=2.1.0
    Depends on vulnerable versions of chokidar
    Depends on vulnerable versions of watchify-middleware
    node_modules/budo
      canvas-sketch-cli  *
      Depends on vulnerable versions of budo
      Depends on vulnerable versions of ora
      node_modules/canvas-sketch-cli
    watchify  3.0.0 - 3.11.1
    Depends on vulnerable versions of chokidar
    node_modules/watchify
      watchify-middleware  *
      Depends on vulnerable versions of watchify
      node_modules/watchify-middleware

9 vulnerabilities (3 moderate, 6 high)

Some issues need review, and may require choosing
a different dependency.

**Comment by snoodler** [comment]
it is working with npx. thanks for the help !

**Comment by fturcheti** [comment]
Nice, @snoodler! As you got it working, I'm closing this issue.

**Comment by ValeGitDev87** [comment]
how can help me? , I have this problem :

**Comment by ValeGitDev87** [comment]
Last login: Thu Mar 10 17:24:55 on ttys000
valentinosciarne@MBPdiValentino ~ % npm install canvas-sketch-cli -g  
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/canvas-sketch-cli
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/canvas-sketch-cli'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/canvas-sketch-cli'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/canvas-sketch-cli'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/valentinosciarne/.npm/_logs/2022-03-10T16_29_11_163Z-debug-0.log
valentinosciarne@MBPdiValentino ~ %  install canvas-sketch CLI locally
