### ISSUE TITLE
Can't run "npm install -g expo-cli"

### ISSUE THREAD

**Issue by virajsabhaya23** [mattdesl/canvas-sketch#148]
<img width="877" alt="Screen Shot 2022-03-05 at 10 53 25 PM" src="https://user-images.githubusercontent.com/77448246/156909774-0a20d7d9-f3b4-456a-a7ff-abcc55ea12ed.png">

- Shows npm ERR when try "npm audit fix --force"
- I also tried clearing the cache

**Comment by mattdesl** [comment]
Closing this thread, but see this comment for installation changes:
https://github.com/mattdesl/canvas-sketch/issues/96#issuecomment-1231548822
