### ISSUE TITLE
I'm having issues installing canvas-skech

### ISSUE THREAD

**Issue by jamahaus** [mattdesl/canvas-sketch#153]
Hi, every time I try to run "npm install canvas-sketch-cli -g" I get the following error:

**_$ npm install canvas-sketch-cli -g
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

changed 669 packages, and audited 670 packages in 4m

55 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities_**

I'm still a rooky and I would really appreciate your assistance with this.

**Comment by juniacosta** [comment]
I'm having the same problem... and when I try to 

# Scaffold a new 'sketch.js' file and open the browser
canvas-sketch sketch.js --new --open

the Git do not respond, and dont make a new .js file

**Comment by juniacosta** [comment]
Hey @jamahaus , I used the Windows Power Shell as a Admin, received the same erros, but following the other steps i could create a .js file.

Power Shell anounced that i have to enable permission to running scripts.

https://social.technet.microsoft.com/wiki/pt-br/contents/articles/35641.windows-10-permitir-a-execucao-de-scripts-no-powershell.aspx 

Hope this help you.

**Comment by mattdesl** [comment]
I've fixed most of the offending warnings in the latest version, but there might still be some that show up. You can ignore the warnings, it should still work fine.

If you are having trouble installing and using, please see here:

https://github.com/mattdesl/canvas-sketch/issues/96#issuecomment-1231548822

I will close this thread for now but if you are still having issues you can post in that other thread.
