### ISSUE TITLE
Two.js template error

### ISSUE THREAD

**Issue by cdaein** [mattdesl/canvas-sketch#156]
Trying to use the default two.js template by running:

```
canvas-sketch sketch.js --new --template=two --open 
```

gives an error:
```
Uncaught (in promise) TypeError: Two is not a constructor
    at sketch (sketch.js? [sm]:11:1)
    at SketchManager.js:967:20
```

There must have been some changes in two.js `0.8.x` upgrade because the sketch runs fine with two.js `0.7.x`.
I am tagging the two.js creator just in case - @jonobr1

**Comment by jonobr1** [comment]
It was actually an issue with how the build systems changed (from Rollup to esbuild). I just made a patch for it here: https://github.com/jonobr1/two.js/issues/643

You can install the latest npm version, `v0.8.10` and it should be resolved. Thanks for sharing!
