### ISSUE TITLE
Record canvas with sound

### ISSUE THREAD

**Issue by jusebin** [mattdesl/canvas-sketch#163]
Hello ! I'm trying to create an audio visualizer
I'm wondering if there is any way to record sound with the canvas-sketch ? 

When I tried to to record hit by typing `ctrl + maj + s`  the video is recorded, but not the sound.

Thank you !

**Comment by mattdesl** [comment]
Unfortunately this is a little complicated, I haven't found a solid way of doing it (but I haven't really tested it beyond just looking into how it could be done). I think for now this is out of scope of canvas-sketch and you'd be better off just doing a regular screen recording, but if anybody has ideas how it could be achieved I'm all ears.
