### ISSUE TITLE
Can't start a new sketch from the Three.js template

### ISSUE THREAD

**Issue by pazuzuuu** [mattdesl/canvas-sketch#164]
Hihi, I used the ```canvas-sketch webgl.js --new --template=three  ``` but I get the following: 
-bash: canvas-sketch: command not found

Not sure how to debug this as I have already installed canvas sketch and I'm able to open/create normal .js files. Newbie here, would greatly appreciate any help!

**Comment by mattdesl** [comment]
Hey there, you can see this comment which should solve your problem:
https://github.com/mattdesl/canvas-sketch/issues/96#issuecomment-1231548822

The command you will use is:

```sh
npx canvas-sketch-cli webgl.js --new --template=three
```
