### ISSUE TITLE
have not been able to install canvas-sketch

### ISSUE THREAD

**Issue by Novaxvx** [mattdesl/canvas-sketch#166]
everytime i tried to inatall with "npm install canvas-sketch-cli -g" this pop up:

npm install canvas-sketch-cli --global
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecatednpm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

changed 672 packages, and audited 673 packages in 30s

57 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

**Comment by andryrave** [comment]
hello. I have the same problem, did you manage to fix it?

**Comment by andrescarta** [comment]
hi guys! same problem!
hope @mattdesl to fix it! 
in the mean while i'm using codesandbox, but it crash often

**Comment by mattdesl** [comment]
Please see this comment for a solution:
https://github.com/mattdesl/canvas-sketch/issues/96#issuecomment-1231548822

I will close this thread for now, but please post in the linked thread if you have further issues installing.
