### ISSUE TITLE
issue opening sketch-01.js

### ISSUE THREAD

**Issue by alfred-011** [mattdesl/canvas-sketch#182]
<img width="413" alt="Screenshot 2023-04-09 at 08 58 10" src="https://user-images.githubusercontent.com/79214420/230762659-c138f8e1-8d3a-4bb9-b888-be22f53a309e.png">

**Comment by Angusatgithub** [comment]
Also getting the same error - can get it to install all dependancies when using `sudo` but then vscode seems to have permission issues editing the files created

**Comment by ReneKrewinkel** [comment]
You need to create a new NodeJS project and add `canvas-sketch` to it. To do so, open up your terminal, and execute following commands:

```shell
mkdir your-dir
cd your-dir
npm init -y
npm install --save-dev canvas-sketch canvas-sketch-util
```

Now you can create a new sketch within that sub dir: 

```shell
canvas-sketch index.js --new --open
```

And if you want to run it later: 

```shell
canvas-sketch index.js --open
```

That should do the trick!

**Comment by alvinometric** [comment]
Thanks René 🙏
