### ISSUE TITLE
Add canvas-sketch as canvas to website

### ISSUE THREAD

**Issue by Gurnoorkalsi** [mattdesl/canvas-sketch#183]
Hi! 

I want to add my canvas-sketch as an animation to my website, which would include other standard html elements.
Specifically, I want to be able to display it as a canvas element (which can be resized according to be viewport).

**Comment by mattdesl** [comment]
Hello, see some of the discussion here:

https://github.com/mattdesl/canvas-sketch/issues/178

And here:

https://github.com/mattdesl/canvas-sketch/blob/master/docs/cli.md#building-to-a-website
