### ISSUE TITLE
Cannot start canvas-sketch-cli: SyntaxError

### ISSUE THREAD

**Issue by baptistebriel** [mattdesl/canvas-sketch#19]
Hey Matt! Wanted to give this a try, but I'm getting a SyntaxError when running `canvas-sketch sketch.js --new --open` — I just followed the install steps in the README and ran into this issue.

![screen shot 2018-09-28 at 3 45 28 pm](https://user-images.githubusercontent.com/2464663/46212240-c7594700-c335-11e8-883f-641e92ce3790.png)

Not sure if I missed something 😅

**Comment by mattdesl** [comment]
You will need a recent version of Node/npm to use the tools, try at least node 8.10.x and npm 6.1.x.

I'll add this to the repo/docs and the tool itself to make it a bit more clear. :smile:

**Comment by baptistebriel** [comment]
Ah, gotcha! Thanks!
