### ISSUE TITLE
Method for saving canvas

### ISSUE THREAD

**Issue by maximakesthings** [mattdesl/canvas-sketch#190]
I want to export the canvas (usually done with ctrl + s) through code.
I'm using Tweakpane and would like to export upon a button being pressed but I can't find a relevant method in the docs.

Would appreciate any guidance :)

```
const createPane = () => {
    const pane = new Tweakpane.Pane({
        title: 'Einstellungen'
    });
    
    const exportButton = pane.addButton({
        title: "Export"
    })

    exportButton.on("click", () => {
        // ?
    })
}
```

**Comment by mattdesl** [comment]
You can call `props.exportFrame()` where `props` is the main parameter to your sketch.

**Comment by maximakesthings** [comment]
Thanks!
In regards to the props, I'm using the standard way described in the docs:

```
const sketch = () => {
    return ({ context, width, height, frame }) => {
       // ...   
    }
};
```
and calling Tweakpane and canvasSketch at the end:

```
createPane();
canvasSketch(sketch, settings);
```
exportFrame() would be a function of what here?
Sorry for the inconvenience.

**Comment by maximakesthings** [comment]
Figured it out, I was a bit confused but figured out the context.
Thanks for the help!

**Comment by mattdesl** [comment]
For future reference for anybody stumbling upon this issue, it looks like this:

```js
const sketch = (props) => {
  myButton.onclick = () => props.exportFrame();
  
  return () => { /* render fn */ };
}
```

Cheers :smile:
