### ISSUE TITLE
how to implement navigator.requestMIDIAccess();

### ISSUE THREAD

**Issue by alexalex25** [mattdesl/canvas-sketch#192]
Hey, i'd like to control some stuff in my sketch with midi.
But wherever i try to navigator.requestMIDIAccess(), i get undefined...

Is it possible to use webMIDI in the sketches ?

Thx!

**Comment by alexalex25** [comment]
Ok, I solved it after reading [this](https://stackoverflow.com/questions/61196127/why-is-requestmidiaccess-working-locally-but-not-remote) : 

It says : 
navigator.requestMIDIAccess() is only available [in a secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts/features_restricted_to_secure_contexts), which means your remote host must serve your resources via HTTPS.

Resources served from localhost [are considered to be in a secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#When_is_a_context_considered_secure), whether delivered via HTTPS or HTTP.

Connect to your remote host using HTTPS instead of HTTP and that should resolve the problem.

So what i did is write localhost:9966 instead of ip_adress:9966 that comes up by default in the url of the navigator.
It works !

**Comment by mattdesl** [comment]
Yes I've run into something similar, bit of a pain when testing. I'll close since `localhost` should do the trick for the most part!
