### ISSUE TITLE
canvas-sketch mysketch.js 

### ISSUE THREAD

**Issue by andresclua** [mattdesl/canvas-sketch#193]
Hi there, I add stopped working with this library for almost 1 year, and today when I run "canvas-sketch mysketch.js" this command it's creating a lot of files like this on my downloads folder.

![32897](https://github.com/mattdesl/canvas-sketch/assets/612806/8ddeba5d-8c33-4da5-ac0f-1eb9abdaba35)
<img width="1272" alt="Captura de pantalla 2023-08-18 a las 0 57 31" src="https://github.com/mattdesl/canvas-sketch/assets/612806/df28310a-927c-4cf7-aa65-5f19c0e0c38b">

super random.

**Comment by andresclua** [comment]
If I do canvas-sketch test.js --output=output/01, it generates automatically inside that folder too

**Comment by andresclua** [comment]
fixed, looks like I need to run `canvas-sketch-cli` instead of `canvas-sketch`.
 
 Probably documentation could be a little more clear.

**Comment by mattdesl** [comment]
You should be able to run `canvas-sketch` (without CLI) if it's installed globally. If it's not installed globally, you'll need to run `npx canvas-sketch-cli` as in the docs.
