### ISSUE TITLE
Problem installing 

### ISSUE THREAD

**Issue by FloMastrangelo** [mattdesl/canvas-sketch#197]
Hi!
I'm on a Mac. I did install node.js v20.11.1, but when I tried to install canvas-sketch globally I couldn't  and it says:

npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

changed 553 packages in 26s

83 packages are looking for funding
  run `npm fund` for details
Flo@MacBook-Air-de-Florencia ~ % npm fund
Flo
├── https://opencollective.com/core-js
│   └── core-js@3.36.1, core-js-bundle@3.36.1, core-js-pure@3.36.1
├── https://github.com/sponsors/ljharb
│   └── deep-equal@1.1.2, is-arguments@1.1.1, call-bind@1.0.7, function-bind@1.1.2, get-intrinsic@1.2.4, has-proto@1.0.3, has-symbols@1.0.3, define-data-property@1.1.4, gopd@1.0.1, has-property-descriptors@1.0.2, has-tostringtag@1.0.2, is-date-object@1.0.5, is-regex@1.1.4, object-is@1.1.6, define-properties@1.2.1, regexp.prototype.flags@1.5.2, functions-have-names@1.2.3, defined@1.0.1, is-object@1.0.2, minimist@1.2.8, resolve@1.22.8, is-core-module@2.13.1, supports-preserve-symlinks-flag@1.0.0, qs@6.12.0, shell-quote@1.8.1, object.assign@4.1.5, is-generator-function@1.0.10, is-typed-array@1.1.13, which-typed-array@1.1.15, available-typed-arrays@1.0.7, is-callable@1.2.7, tape@4.17.0, mock-property@1.0.3, object-inspect@1.12.3, string.prototype.trim@1.2.9, es-abstract@1.23.2, array-buffer-byte-length@1.0.1, arraybuffer.prototype.slice@1.0.3, data-view-buffer@1.0.1, data-view-byte-length@1.0.1, data-view-byte-offset@1.0.0, es-to-primitive@1.2.1, is-symbol@1.0.4, function.prototype.name@1.1.6, get-symbol-description@1.0.2, globalthis@1.0.3, is-array-buffer@3.0.4, is-data-view@1.0.1, is-negative-zero@2.0.3, is-shared-array-buffer@1.0.3, is-string@1.0.7, is-weakref@1.0.2, safe-array-concat@1.1.2, safe-regex-test@1.0.3, string.prototype.trimend@1.0.8, string.prototype.trimstart@1.0.7, typed-array-byte-length@1.0.1, typed-array-byte-offset@1.0.2, typed-array-length@1.0.5, unbox-primitive@1.0.2, has-bigints@1.0.2, which-boxed-primitive@1.0.2, is-bigint@1.0.4, is-boolean-object@1.1.2, is-number-object@1.0.7
├─┬ https://opencollective.com/babel
│ │ └── @babel/core@7.24.1
│ └── https://opencollective.com/browserslist
│     └── browserslist@4.23.0, caniuse-lite@1.0.30001599, update-browserslist-db@1.0.13
├── https://github.com/sponsors/sindresorhus
│   └── pretty-bytes@5.6.0, binary-extensions@2.3.0, is-finite@1.1.0, defaults@1.0.4
├── https://github.com/sponsors/isaacs
│   └── glob@7.2.3
├── https://github.com/sponsors/feross
│   └── safe-buffer@5.2.1, base64-js@1.5.1, ieee754@1.2.1, simple-concat@1.0.1, run-series@1.1.9
└─┬ https://paulmillr.com/funding/
  │ └── chokidar@3.6.0
  └── https://github.com/sponsors/jonschlinkert
      └── picomatch@2.3.1

I can't get the problem :(

**Comment by Eidan78** [comment]
me too!

**Comment by mattdesl** [comment]
Have you tried using npx to run it locally?

https://github.com/mattdesl/canvas-sketch

`npx canvas-sketch-cli blah.js` will run it anywhere. 


To run it over and over again without installing each time: you can cd into a new folder, type `npm init -y && npm install canvas-sketch-cli` then you will be able to run `npx canvas-sketch blah.js` (no -cli this time) which will use the locally installed one.

**Comment by LucasMERN** [comment]
This does not run for me on Node v20 either. I installed nvm to install 16 and switched to 16 and it runs fine.

**Comment by mattdesl** [comment]
I've just changed a feature that may help even when node version is >= 18. Unfortunately I don't have access to Windows right now.

Can you try updating the CLI?

If you are using it globally:

```js
npm i canvas-sketch-cli@1.15.0 --global

mkdir test-sketch
cd test-sketch
canvas-sketch sketch.js --new
```

Or if you are using it with `npx`:

```js
mkdir test-sketch
cd test-sketch
npx canvas-sketch-cli@1.15.0 sketch.js --new
```

Or if you are using it with locally installed devDependency:

```js
mkdir test-sketch
cd test-sketch
npm init -y

npm install canvas-sketch-cli@1.15.0 --save-dev
npx canvas-sketch sketch.js --new
```

**Comment by LucasMERN** [comment]
Whatever you did worked. Working fine on windows with npm. My previous comment about not being able to use it with Nextjs was not valid. I am just bad at coding. haha. I gave up trying to use it with Next. Could not figure out how to get any of the GLSL code to work at all.
