### ISSUE TITLE
Add npx to quick start

### ISSUE THREAD

**Issue by olhapi** [mattdesl/canvas-sketch#24]
I propose to add **npx** to quick start section. Fellas that don't like installing packages globally will be grateful.
**npx** installs with npm by default starting with npm@5.2.0

More info here - https://blog.npmjs.org/post/162869356040/introducing-npx-an-npm-package-runner

**Comment by mattdesl** [comment]
Thanks! IMHO using `npx` is more complex and [error-prone](https://github.com/npm/npm/issues/19673), so I don't want to advocate for it in the quick start.

In any case, I've added some details on local installation in the [installation instructions](https://github.com/mattdesl/canvas-sketch/blob/master/docs/installation.md#installing-the-cli-locally).

**Comment by olhapi** [comment]
Great :) @mattdesl, thanks for clarifying.
