### ISSUE TITLE
p5js example should demonstrate accessing p5 in setup

### ISSUE THREAD

**Issue by pbeshai** [mattdesl/canvas-sketch#29]
In the p5js examples, there are comments indicating where the equivalent of setup is:

```js
canvasSketch(() => {
  // Inside this is a bit like p5.js 'setup' function
  // ...
```

At least for the instanced version, you need access to the p5 instance there, but it's not clear how to get it from the current example. Updating the code to have:

```js
canvasSketch(({ p5 }) => {
  // Inside this is a bit like p5.js 'setup' function
  // ...
```

would help clarify it.

**Comment by mattdesl** [comment]
In the global (non-instanced) version, you don’t need to use p5 as a prop as all its functions and variables exist on the global scope already.  Does that make sense ?
