### ISSUE TITLE
createShader should indicate it uses regl

### ISSUE THREAD

**Issue by pbeshai** [mattdesl/canvas-sketch#31]
It would be helpful to know that the createShader util uses regl behind the scenes. It took me a while to figure this out when attempting to repurpose [the shader created in your gist here](https://gist.github.com/mattdesl/854906361159c2694e5ad8eadde4eee7) to work with Three.

**Comment by mattdesl** [comment]
Good call. Will accept PRs to fix up the docs - otherwise I will get around to it later in the week. Thanks!
