### ISSUE TITLE
Automatically add .js extension when creating new sketch

### ISSUE THREAD

**Issue by pbeshai** [mattdesl/canvas-sketch#33]
A couple of times I've forgotten to include the `.js` and have had to rename my file afterward and restart the canvas-sketch server. Would be nice if the CLI automatically added it for you if not provided.

For example, I wrote:

```
canvas-sketch sketches/molnar-quads --hot --new --output=output/
```

Then rename to molnar-quads.js, kill the server, start again as:

```
canvas-sketch sketches/molnar-quads.js --hot --output=output/
```

(btw I'm happy to submit PRs for any of the issues I've submitted if you think they're worthwhile!)

**Comment by mattdesl** [comment]
Good idea! I can look into this in the next few days after GROW festival things are finished.
