### ISSUE TITLE
Possibly outdated example?

### ISSUE THREAD

**Issue by joshwcomeau** [mattdesl/canvas-sketch#37]
In the [`canvas-penplot.js`](https://github.com/mattdesl/canvas-sketch/blob/master/examples/canvas-penplot.js) example, a utility is imported, `exportPolylines`, and used in a return array (https://github.com/mattdesl/canvas-sketch/blob/master/examples/canvas-penplot.js#L28) to generate an SVG. Another example, [`pen-plotter-patchwork.js`](https://github.com/mattdesl/canvas-sketch/blob/b442454fa7b7e19ceb70292fd1de88703f66305b/examples/pen-plotter-patchwork.js#L2), imports it from `canvas-sketch-util/penplot`.

I tried doing this in my own project, but the import didn't resolve. But, I soon realized that it was OK, since I was indeed getting an SVG when saving the file. So I'm guessing this utility isn't needed, it happens automatically?

I'm happy to open a PR to update the examples, but I wanted to solidify my understanding first. Are SVGs always generated, or does it have to be returning a format compatible with SVG rendering, like polylines?

EDIT: just saw the relevant docs, [exporting-artwork.md](https://github.com/mattdesl/canvas-sketch/blob/master/docs/exporting-artwork.md). It answers some of my questions... although my work is getting an SVG without specifying an `encoding` in settings, so it's still not clear to me what the conditions are for SVG output.

**Comment by mattdesl** [comment]
Thanks! `canvas-penplot.js` was indeed legacy, I've now removed it. See the following examples for how to use the pen plotter (SVG) export:

- [pen-plotter-circles.js](https://github.com/mattdesl/canvas-sketch/blob/master/examples/pen-plotter-circles.js) – simple example with penplot and polyline clipping to a margin
- [pen-plotter-patchwork](https://github.com/mattdesl/canvas-sketch/blob/master/examples/pen-plotter-patchwork.js) – more manual control over rendering & exporting

SVG is not exported automatically, and there is no built-in logic in `canvas-sketch` to handle files like SVG (mapping Canvas2D to SVG would be a massive and painful undertaking). Instead, you can export arbitrary file formats by returning a file descriptor in the form of `{ data, extension }` – see below:

```js
canvasSketch(() => {
  return ({ context, width, height } => {
    // Generate some data, optionally render into canvas
    // context if you want to visualize it in the browser.
    // ...

    // Here, we export a JSON file instead of a PNG file on Cmd + S export
    return {
      data: JSON.stringify({ foo: 'bar' }),
      extension: '.json'
    };
  };
});
```

This is how I'm using canvas-sketch for things other than images, like: turning polyline lists into SVG (e.g. AxiDraw pen plotter, or an industrial laser cutter), JSON (e.g. metadata alongside exported images) exporting parametric 3D models as GLTF or OBJ (e.g. for Blender, 3D printing, or paper model folding).

The `canvas-sketch-util` includes a `penplot` module which turns a list of polylines into an AxiDraw-compatible SVG string. When using the feature (as in `examples/pen-plotter-circles.js`) this means that, when hitting `Cmd + S`, you will get both a PNG and SVG file from the artwork.

There's a few more details here:

https://github.com/mattdesl/canvas-sketch/blob/master/docs/exporting-artwork.md#exporting-other-file-types

If you have other questions just ask. :smile: There are a lot of little details hidden in the docs, I realise, and I'd like to find better ways to bring those to the surface.

**Comment by joshwcomeau** [comment]
Hi Matt! Thanks for the detailed response =)

Ah, that's interesting! I like how elegant that is; utilities control their own output formats, by abstracting it away in the renderer (like `renderPolylines`).

> This is also how the fullscreen shader utility module works. I'll probably be adding others over time, for example handling silkscreen/risograph printing (layer masks), laser cutters, CNC machines, etc.

Exciting!

Closing the issue, since the original concern's been addressed :)
