### ISSUE TITLE
Hitting Cmd+S saves the wrong picture and re-renders the canvas 

### ISSUE THREAD

**Issue by dutzi** [mattdesl/canvas-sketch#51]
Not sure what caused this, but when I hit Cmd+S the wrong picture is saved and the art board re-renders

**Comment by mattdesl** [comment]
Can you provide a small code sample?

**Comment by dutzi** [comment]
This one, for example:

```js
import canvasSketch from 'canvas-sketch';
import random from 'canvas-sketch-util/random';

const settings = {
  dimensions: 'a4',
};

const sketch = () => {
  return ({ context, width, height }) => {
    context.fillStyle = 'white';
    context.fillRect(0, 0, width, height);
    context.fillStyle = 'black';
    context.fillRect(0, 0, random.range(0, width), height);
  };
};

canvasSketch(sketch, settings);
```

The thing is is happens no matter what I code...

**Comment by mattdesl** [comment]
Ah yep. Render is called on save as props have changed (for example an ‘exporting’ prop, and depending on your settings the canvas size may be different on export). So you should not introduce side effects in the render function. See below for details:

https://github.com/mattdesl/canvas-sketch/blob/master/docs/hello-world.md#props--state

**Comment by dutzi** [comment]
Ah, got it. Thanks!

**Comment by mattdesl** [comment]
Will close as this isn't an issue, but it does present a potential area for improved documentation.
