### ISSUE TITLE
FPS rate only works if 'playbackRate' is set to throttle

### ISSUE THREAD

**Issue by Mamboleoo** [mattdesl/canvas-sketch#58]
I was trying to force a lower FPS by setting the property `fps: 4` in my settings (as shown in the docs https://github.com/mattdesl/canvas-sketch/blob/master/docs/animated-sketches.md) but I couldn't make it work unless I also defined the `playbackRate` to `throttle`.

I dug a bit in the source code and I found that without the `playbackRate` the fps value was never taken into account.
https://github.com/mattdesl/canvas-sketch/blob/4addd0fe3fc053065ca8597ab204e43587c52879/lib/core/SketchManager.js#L621

I don't know if it should be set to `throttle` as a default but I think it should be mentioned in the docs :)

Thanks for the library btw 💙

**Comment by mattdesl** [comment]
Yup this is something that might need better documentation and a bit more thought around.

I didn't want to throttle FPS by default as the real-time animation will feel slightly less fluid. So without throttling, the `fps` setting is still used (it affects total frame count and `deltaTime` interval on animation export), but you won't notice a difference when watching the animation loop in the browser.

**Comment by Mamboleoo** [comment]
Thanks for the reply, it makes sense now!
