### ISSUE TITLE
Possiblity to customize the html a bit more

### ISSUE THREAD

**Issue by ELI7VH** [mattdesl/canvas-sketch#60]
any way you could make the root html exposed so we can style and build from as needed?

**Comment by mattdesl** [comment]
Hey, this should be possible already with the `--html` flag, see this part of the docs for details:

https://github.com/mattdesl/canvas-sketch/blob/master/docs/cli.md#building-to-a-website

**Comment by ELI7VH** [comment]
ah many thanks! working my way thru the docs now!
