### ISSUE TITLE
Does this work in nodejs/cairo

### ISSUE THREAD

**Issue by shash7** [mattdesl/canvas-sketch#64]
Hi

I was wondering whether this library works at all inside nodejs using cairo(node-canvas)?

**Comment by mattdesl** [comment]
Yes the `canvas` passed into settings just needs to resemble an HTML5 canvas, so it can use node-canvas or headless-gl modules:

Here's an example of using node-canvas:

https://github.com/mattdesl/canvas-sketch/blob/master/docs/exporting-artwork.md#node-export

And here's an example of using headless-gl:

https://github.com/mattdesl/canvas-sketch/blob/master/examples/headless-gl.js

I'm open to discussion about how to make both of these features a bit easier and more accessible. Most of my work has been in the browser but occasionally I will need to use node.js to automate sketch exporting and/or produce really large resolution images.

**Comment by shash7** [comment]
Hey this is exactly what I was looking for. Thanks!

**Comment by mattdesl** [comment]
Good to hear! Closing as it seems resolved.
