### ISSUE TITLE
PerspectiveCamera() doesn't work

### ISSUE THREAD

**Issue by okspry** [mattdesl/canvas-sketch#66]
When I switch from orthographic to perspective camera, nothing shows up. It doesn't matter how large I make the meshes or what numbers I pass into PerspectiveCamera().

Currently, I have a mesh with a radius of 20 and have tried adding a perspective camera with 

new THREE.PerspectiveCamera(35, width / height, 1, 1000);

**Comment by kellymilligan** [comment]
Hey @okspry , have you set the position of your camera? It's possible that your camera is at the scene origin (0, 0, 0), along with your mesh; meaning that your camera is actually inside the mesh.

try adding `camera.position.set( 0, 0, 50 )`

**Comment by okspry** [comment]
Thanks @

**Comment by mattdesl** [comment]
Going to close as it seems resolved. Cheers!
