### ISSUE TITLE
Cannot find module from '_fake.js'

### ISSUE THREAD

**Issue by ktim816** [mattdesl/canvas-sketch#67]
When I run the command, I get the following error (https://www.screencast.com/t/vSxQHgZf, https://www.screencast.com/t/PBxHKzAUVvMy). Tried to reinstall the canvas-sketch-cli globally, converted to ES6 Modules, but to no avail. Has anyone already come across this?

**Comment by ktim816** [comment]
The problem was that I initially ran the command canvas-sketch without installation via npm. Tried to install via npm, and that works

**Comment by david-bulte** [comment]
Hi @mattdesl I'm running into the same problem. I have followed all steps from the quick-start, but I keep getting this error ("Error: Cannot find module 'C:\temp\my-sketches\c' from '_fake.js''"). 

My environment:

- windows
- node v10.14.1
- npm v6.13.6

Thanks

**Comment by david-bulte** [comment]
It's probably because I'm running on Windows. When I run the script in a bash shell, I do see the expected blank canvas.

**Comment by mattdesl** [comment]
@david-bulte Can you explain what you mean by running on Windows as opposed to a bash shell?

I usually suggest using a console emulator like [cmder](https://cmder.net/) on windows. You can open the cmder shell and install like so:

```sh
npm install canvas-sketch-cli --global
```

Then, you can `cd` to a new folder and generate a new sketch:

```sh
canvas-sketch sketch.js --new --open
```

**Comment by david-bulte** [comment]
@mattdesl Sorry I'm not very good with these terms. I mean if I run the command from the Command Line it doesn't work. I have also installed Git Bash, and if I run it from that, it works. 

Cmder looks interesting, will check it out. Thanks!
