### ISSUE TITLE
Cannot get library up and running on latest master

### ISSUE THREAD

**Issue by ricardomatias** [mattdesl/canvas-sketch#69]
I'm using the latest master and most npm commands are failing.

* `npm run lib` & `npm start`

```
> node website/dev.js

[0000] info  Server running at http://localhost:9966/ (connect)

/Users/xxx/Creative-Coding/canvas-sketch-lib/node_modules/nanomatch/lib/compilers.js:213
      var before = prev.prev || {};
                        ^

TypeError: Cannot read property 'prev' of undefined
```

Or is the current state assuming that the development is done by linking to another project?

PS:
Not sure if there should be an issue for this, since it's related to a transitive dependency, but at the moment node v12 isn't working because of google/angle (C++ bindings errors).

**Comment by mattdesl** [comment]
The website stuff is legacy, I am going to start removing that from this repo and eventually create a new repo to hold that.

For now you can do this:

```sh
# start watching changes in the library code
npm run lib:watch

# use global canva-sketch to test
canvas-sketch examples/some-example.js
```

When you make changes to the library code, it should trigger a reload in the example. Sometimes you'll have to reload manually.

Overall, the development experience when cloning this repo is not ideal.

Of course, if you are just wanting to use `canvas-sketch` and/or its CLI, and don't have plans to modify this repo's source code, then you shouldn't need to clone the repo in the first place.

**Comment by ricardomatias** [comment]
Fair enough. I want to dig in the actual library, trying to understand what can be done to extend it or what is better off done externally. Cheers.
