### ISSUE TITLE
Add --help command line argument

### ISSUE THREAD

**Issue by vvzen** [mattdesl/canvas-sketch#71]
Hi!
Thanks for working on this project, I feel it's a very handy way to manage creative sketches written in js and a great way to kickstart inspiration.

While trying it, I was wondering why the command line tool doesn't have a `canvas-sketch --help` functionality. I think it would be nice to just have a recap of the commands you can enter without having to leave the shell (the dearest of a programmer's friends).
Or maybe I'm just too used to python where every cli tool comes with a nice --help or -h option. 😄 

Thanks!

**Comment by mattdesl** [comment]
Thanks! I agree a help flag would be great. Happy to merge in a PR (you can see github.com/mattdesl/budo for how I handled it there), or otherwise I’ll try to get around to it at some point!

**Comment by vvzen** [comment]
I'm a little bit rusty with nodejs but I'll see what I can do! :)

**Comment by vvzen** [comment]
I made a quick PR here: https://github.com/mattdesl/canvas-sketch-cli/pull/5
