### ISSUE TITLE
FPS in animated gifs

### ISSUE THREAD

**Issue by tommypreger** [mattdesl/canvas-sketch#72]
Is it only me or do gifs get exported with incorrect fps?

When using fps: 24, both gif and mp4 outputs at similar speed, but when setting framerate to something higher it seems like the gif is only getting slower while the mp4 gets smoother as expected. Any idea why this is?

**Comment by mattdesl** [comment]
Yup this is a bug, looking into it now! Thanks for the report.

**Comment by mattdesl** [comment]
So, it seems its not really a bug, but more a limitation of GIFs. GIF is encoded with a delay between frames, and with say 60 FPS you should end up with 1/60 second between frames, but most GIF players do not seem to support such small delays between frames. Instead, most players seem to allow only as fast as 50 FPS (0.02 sec delay) before it starts to produce choppy/unusual results.

I just tested by encoding a 60 FPS GIF from Photoshop and it seems to produce the same choppy output. However, 50 FPS GIFs seem to be alright. I would suggest keeping your GIFs in the 24-40 FPS range, and using MP4 if you need higher framerates.

I've pushed some changes in the latest `canvas-sketch-cli@1.9.1` including:

- Terminal logs a warning if you use `--stream=gif` and higher than 50 FPS
- Fixed a bug with file name getting truncated on `--stream` exports
- Added some additional flags to the GIF encoding to make sure input/output framerate matches

You can update like so:

```sh
# if you installed it globally
npm install canvas-sketch-cli --global

# or, if you had installed it locally
npm install canvas-sketch-cli --save-dev
```

**Comment by tommypreger** [comment]
Thanks for looking into it! I'm sure I've seen 60fps-ish gifs out there though?
Either way, mp4 works for me. Loving canvas-sketch so far! I was thinking of creating someting similar for the longest time, but now I don't have to! :)

**Comment by mattdesl** [comment]
Glad to hear! And if you find any 60FPS gifs feel free to link them here and I’ll look into how they were encoded.

**Comment by mattdesl** [comment]
Going to close this as it seems like 60FPS isn't possible, feel free to correct me otherwise though!
