### ISSUE TITLE
Reload on imported module update

### ISSUE THREAD

**Issue by polyclick** [mattdesl/canvas-sketch#84]
Hi

Can we let canvas-sketch parse & reload when an imported custom module/class is updated?

Some projects get quite big to keep all the code in 1 sketch file. I sometimes need extra (custom) modules/classes to seperate out the code from the main entry canvas-sketch file.

When I now update the code in a linked file, I need to restart canvas-sketch and manually reload.
Maybe this is just an option? Any ideas?

Cheers!

**Comment by mattdesl** [comment]
Hey @polyclick , are you importing modules like this from within your main `sketch.js` ?

```js
import myUtil from './util.js';
```

Or with CommonJS:

```js
const myUtil = require('./util.js');
```

This should be supported out of the box, and any changes to `util.js` (or any of its dependencies) should trigger a live-reload as well. If that doesn't work for you, perhaps it has something to do with the file watcher—maybe try re-installing a newer version of Node.js and then re-installing the CLI tool globally?

**Comment by polyclick** [comment]
Hi Matt!

I've upgraded node from `13.5.0` to `13.6.0`, removed `node_modules` and reinstalled `canvas-sketch-cli` to version: `1.11.7`

This indeed solved the problem.

Thanks for the reply and the great work on canvas-sketch, really loving it! :)
