### ISSUE TITLE
[Discussion] Export function on renderer objects

### ISSUE THREAD

**Issue by debone** [mattdesl/canvas-sketch#86]
First of all, thanks for `canvas-sketch`! I have been playing with it and I really found helpful in writing GA with JavaScript :).

For the discussion, after some time writing some sketches I wanted to write it using [Renderer Objects](https://github.com/mattdesl/canvas-sketch/blob/master/docs/api.md#renderer-objects) to make it easier to extract some more broad functionality of my sketches. As it is encouraged to open an issue to discuss them, here it goes.

---

The renderer object accepts `preExport` and `postExport` functions, but not the `export` itself. I wanted to have the export extracted from my sketches, to not copy it everywhere. I end up hacking it into `canvas-sketch` by adding these lines to `_doExportFrame` in `SketchManager.js:332`:

```javascript
if (typeof this.sketch.export === 'function') {
  drawResult = this.sketch.export(canvas);
}
```

I was not that happy with that random `canvas` showing up there so I wanted to know if this could be approached in some other way and see others opinions.

**Comment by mattdesl** [comment]
Hey thanks for the input. Right now the render() function is actually the export — if you return an object or array from the render function, it will be used as drawResult while exporting. You can use props.exporting to conditionally return something in render if you’d rather it not run each frame. 

Hope that helps?

I guess technically it could have been split into its own export function but it would be a major breaking change and lead to a new way of writing sketches.

**Comment by debone** [comment]
That makes sense.

I was trying to achieve something like:

```javascript
class BasicSketch {
  export() {
    // Generic exporting
  }
}

class Sketch extends BasicSketch {
  render() {
    // No worried about exporting
  }
}
```

But now with your insight I see this is the way to go:

```javascript
class BasicSketch {
  // ...
  render(sketchData) {
    if (sketchData.exporting) {
      this.export()
    }
    else {
      this.sketchRender(sketchData)
    }
  }
}

class Sketch extends BasicSketch {
  sketchRender({ ... }) {
    // ...
  }
}
```

Thanks!


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mattdesl** [comment]
Ah, I see. I haven't tried too many class-based approaches (canvas-sketch is designed to be used a little more functionally, similar to how React pushes for functional components).

I think you should still render *before* exporting, otherwise you might end up exporting the previously-rendered result (which may not be the correct resolution).

Here's how you could write this:

```js
const canvasSketch = require('canvas-sketch');

const settings = {
  dimensions: [ 2048, 2048 ]
};

class BasicSketch {
  draw () {} // to be implemented
  render (props) {
    this.draw(props);
    if (props.exporting) {
      return this.export(props);
    }
  }
  export (props) {
    return [
      props.canvas,
      // You may want to export other things...
      // { data: 'hello', extension: '.txt' }
    ];
  }
}

class MySketch extends BasicSketch {
  draw ({ context, width, height }) {
    context.fillStyle = 'red';
    context.fillRect(0, 0, width, height);
  }
}

const sketch = (props) => new MySketch(props);
canvasSketch(sketch, settings);
```

**Comment by debone** [comment]
Thanks for the snippet, I see now. I will make use of it and consider if functional would make things easier on my side. I'm still figuring out how to render stuff smaller on preview while manipulating pixels, so so far I have only a single resolution.
