### ISSUE TITLE
Exporting animation low performances

### ISSUE THREAD

**Issue by Mamboleoo** [mattdesl/canvas-sketch#94]
Hello,
So today I was working on an animation and I noticed when exporting that the performances was getting slower and slower.
You can see in this screencast that when I start exporting my animation it goes super fast but then it gets slower and slower.
It quickly takes >1s per frame and after 100sec each frame takes a very long time.
https://mamboleoo.be/random/canvas-skech-export.mp4

The screencast is on Edge, but Firefox was experiencing the same.
Is there something I should know to optimize my code for better exports?
I can share my code in dm if it can help debugging this issue :)

Thanks,
Louis

**Comment by mattdesl** [comment]
Odd, I’ve never seen this before - does it happen on every sketch or could there be something in your sketch that is causing it ?

**Comment by Mamboleoo** [comment]
I made a very basic setup and try to export it but I'm having the same issue.
Here is the code I'm running:
```
const canvasSketch = require('canvas-sketch');
const settings = {
  dimensions: [ 800, 800 ],
  animate: true,
  duration: 6,
  fps: 60
};

const sketch = () => {
	return {
		render ({ context, width, height, frame }) {}
	}
};

canvasSketch(sketch, settings);
```

It just took ~15min to export the 360 png. The png are not big, 13ko, 1200x1200 with nothing but a transparent square :(

**Comment by Mamboleoo** [comment]
Sorry for spamming I just found the reason of this two minutes after posting previous comment.
I tried the same code but this time without specifying the output folder  `--output=export/` and it works perfectly!
So I guess there must be something running on each export when specifying the output folder making the program slower & slower...

I can live with my exports being in my downloads folder so you can close this issue if you don't think it needs more debugging!
Sorry again for not trying that solution earlier...

**Comment by mattdesl** [comment]
I don't think this should happen in latest version but if anybody notices a certain output folder being slower than others please let me know.
