### ISSUE TITLE
Slow rendering with large paths?

### ISSUE THREAD

**Issue by thetylerwolf** [mattdesl/canvas-sketch#98]
My comp is drawing directly with the canvas API. It has a lot of polygons with long paths (around 300 polys with about 800 points each). Not doing anything unusual:

```
function drawPolygon(points) {
    points.forEach((point,i) => {

      let from = point,
        to = points[i+1]

      if(!to) return

      if(!i) context.moveTo(from.x, from.y)
      context.lineTo(to.x, to.y)

    })

    context.closePath()

    context.fill()
  }
```

Without canvas-sketch, this takes about 14 seconds to render. With canvas-sketch imported, but run with webpack, it takes about 30 seconds and with canvas-sketch CLI, it takes several minutes. When I run on a node server through canvas-sketch, it takes much, much longer.

Am I doing something wrong, or do these complex polygons cause slowdown?

**Comment by thetylerwolf** [comment]
Found when I call context.beginPath() before drawing each polygon, things speed up considerably, but it still takes measurably longer than without canvas-sketch

**Comment by mattdesl** [comment]
You need to call `context.beginPath()` before each shape, otherwise it will continually add shapes to each other for each frame and slow things down / lead to a memory error eventually.

Not sure why webpack would run any differently—are you referring to the act of exporting to a PNG, or simply rendering a frame on a canvas?

It sounds like a pretty unusual bug, I'd love to see a test case that can reproduce this as I haven't run into any noticeable difference between canvas-sketch-cli / rollup / parcel / etc (used it in various bundlers, but never tried webpack).

**Comment by thetylerwolf** [comment]
I’ve been rendering a single frame to canvas. It’s a lot of geometry rendering. I’ll do some tests/investigate further to see if I can find the bottleneck.

**Comment by thetylerwolf** [comment]
Ok, I’ve done some thorough testing with this. The code is kind of complicated, but I’m basically layering hundreds of randomly-shaped polygons at very low opacity (.015). I used the same two colors for testing.

-Rendering takes about the same amount of time when running through webpack vs canvas-sketch (12s vs 11.28s at 1024x1024). I don’t know why, but for a while, the art would finish rendering (canvas-sketch promise would fire), then the browser would hang for almost as long as it took to render the composition. Now it doesn’t and I'm not sure why 😅
-rendering to node-canvas takes considerably longer than rendering in the browser (60s vs 40s for an a4) and color blending seems to work differently (see attached images. node-canvas is more blue and browser is more green.)

![Screenshot 2020-06-09 at 11 50 48](https://user-images.githubusercontent.com/5056789/84133585-9ce6e900-aa47-11ea-9ba6-f2f765d962d4.png)

![Screenshot 2020-06-09 at 11 44 47](https://user-images.githubusercontent.com/5056789/84133447-7cb72a00-aa47-11ea-9697-7abb864dd4d9.png)

Anyway, I'm going to close the issue because it looks like my original problem came from a few bugs that got picked up while migrating from my old code. Hopefully the above is helpful information regardless.
