### ISSUE TITLE
Documentation about adding modules

### ISSUE THREAD

**Issue by edap** [mattdesl/canvas-sketch#99]
Hello Matt, I would like to use canvas-sketch with some custom module (using `import`). I am trying to simply add:
```
  "dependencies": {
    "canvas-sketch": "^0.7.3",
    "my-module":"file:./my_module"
  }
```

But it does not work, but says that it can not find the file. Do you have an example somewhere using import with canvas-sketch ?

**Comment by kellymilligan** [comment]
@edap, when using local modules you don't need to worry about importing them in `package.json`, simply use `require` (common JS, works with node) or `import` (ES6, only works in-browser) to import the package:

```
// Your sketch.js file

const myModule = require('./my_module')
// or...
import myModule from './my_module')
```

**Comment by edap** [comment]
Hello Kelly, i was trying to integrate another library (with its own folder structure) into canvas-sketch, but probably it make sense to import the file that I need as you were suggesting.
Thanks ;)
